server:
  port: 8888
spring:
  application:
    name: config-server

  profiles:
    active: git
---
spring:
  cloud:
    config:
      server:
        native:
          search-locations: C:\Users\rocke\IdeaProjects\ms-config-properties\{application}\{profile}
  config:
    activate:
      on-profile: native
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Viktor-Kollegov/ms-config-properties
          search-paths:
          - "/{application}/{profile}"
#    https://github.com/ksereda/Java_Advanced_Course/

  config:
    activate:
      on-profile: git

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

